package main

import (
	"fmt"
	"os"
	"slices"
	"strings"

	"game-admin/backend/internal/servicedef"
)

func main() {
	out := os.Stdout
	if len(os.Args) > 1 && strings.TrimSpace(os.Args[1]) != "" {
		file, err := os.Create(strings.TrimSpace(os.Args[1]))
		if err != nil {
			fmt.Fprintf(os.Stderr, "create output file: %v\n", err)
			os.Exit(1)
		}
		defer file.Close()
		out = file
	}

	fmt.Fprint(out, renderCompose())
}

func renderCompose() string {
	var builder strings.Builder
	builder.WriteString("# Code generated by backend/cmd/render-microservice-compose; DO NOT EDIT.\n")
	builder.WriteString("version: '3.9'\n\n")
	builder.WriteString("x-backend-common: &backend-common\n")
	builder.WriteString("  image: golang:1.25\n")
	builder.WriteString("  working_dir: /app/backend\n")
	builder.WriteString("  volumes:\n")
	builder.WriteString("    - ./:/app\n")
	builder.WriteString("  environment: &backend-env\n")
	builder.WriteString("    APP_ENV: development\n")
	builder.WriteString("    DATABASE_DRIVER: mysql\n")
	builder.WriteString("    DATABASE_DSN: gameadmin:gameadmin@tcp(mysql:3306)/game_admin?charset=utf8mb4&parseTime=True&loc=Local\n")
	builder.WriteString("    REDIS_ENABLED: \"true\"\n")
	builder.WriteString("    REDIS_ADDR: redis:6379\n")
	builder.WriteString("    REDIS_PASSWORD: \"\"\n")
	builder.WriteString("    REDIS_DB: \"0\"\n")
	builder.WriteString("    REDIS_PREFIX: game-admin:\n")
	builder.WriteString("    MQ_ENABLED: \"true\"\n")
	builder.WriteString("    MQ_DRIVER: rabbitmq\n")
	builder.WriteString("    MQ_URL: amqp://guest:guest@rabbitmq:5672/\n")
	builder.WriteString("    MQ_TOPIC: game-admin.events\n")
	builder.WriteString("  depends_on:\n")
	builder.WriteString("    mysql:\n")
	builder.WriteString("      condition: service_healthy\n")
	builder.WriteString("    redis:\n")
	builder.WriteString("      condition: service_started\n")
	builder.WriteString("    rabbitmq:\n")
	builder.WriteString("      condition: service_started\n\n")

	builder.WriteString("services:\n")
	for _, name := range sortedHTTPServiceNames() {
		builder.WriteString(renderMigrateService(name))
	}
	builder.WriteString(renderGatewayService())
	for _, name := range sortedHTTPServiceNames() {
		builder.WriteString(renderHTTPService(name))
	}
	for _, name := range sortedWorkerServiceNames() {
		builder.WriteString(renderWorkerService(name))
	}
	builder.WriteString(renderFrontendService())
	builder.WriteString(renderInfraServices())
	return builder.String()
}

func sortedHTTPServiceNames() []string {
	items := servicedef.HTTPNames()
	slices.Sort(items)
	return items
}

func sortedWorkerServiceNames() []string {
	items := servicedef.WorkerNames()
	slices.Sort(items)
	return items
}

func renderMigrateService(name string) string {
	return fmt.Sprintf("  migrate-%s:\n    <<: *backend-common\n    command: sh -c 'go run ./cmd/migrate-service %s'\n    profiles: [\"migrate\"]\n\n", name, name)
}

func renderGatewayService() string {
	var builder strings.Builder
	builder.WriteString("  gateway:\n")
	builder.WriteString("    <<: *backend-common\n")
	builder.WriteString(fmt.Sprintf("    command: %s\n", renderLoggedCommand("gateway-service", "./cmd/gateway-service")))
	builder.WriteString("    environment:\n")
	builder.WriteString("      <<: *backend-env\n")
	for _, name := range sortedHTTPServiceNames() {
		def := servicedef.MustHTTP(name)
		envKey := gatewayEnvKey(name)
		builder.WriteString(fmt.Sprintf("      GATEWAY_%s_URL: http://%s:%s\n", envKey, name, def.DefaultPort))
	}
	for _, name := range sortedWorkerServiceNames() {
		def := servicedef.MustWorker(name)
		envKey := gatewayEnvKey(name)
		builder.WriteString(fmt.Sprintf("      GATEWAY_%s_URL: http://%s:%s\n", envKey, name, def.DefaultPort))
	}
	builder.WriteString("    ports:\n")
	builder.WriteString("      - \"8080:8080\"\n")
	builder.WriteString("    depends_on:\n")
	for _, name := range sortedHTTPServiceNames() {
		builder.WriteString(fmt.Sprintf("      %s:\n        condition: service_started\n", name))
	}
	for _, name := range sortedWorkerServiceNames() {
		builder.WriteString(fmt.Sprintf("      %s:\n        condition: service_started\n", name))
	}
	builder.WriteString("\n")
	return builder.String()
}

func renderHTTPService(name string) string {
	def := servicedef.MustHTTP(name)
	return fmt.Sprintf("  %s:\n    <<: *backend-common\n    command: %s\n    environment:\n      <<: *backend-env\n      METRICS_PORT: %s\n    ports:\n      - \"%s:%s\"\n\n", name, renderLoggedCommand(name, "./cmd/"+name), def.DefaultPort, def.DefaultPort, def.DefaultPort)
}

func renderWorkerService(name string) string {
	def := servicedef.MustWorker(name)
	return fmt.Sprintf("  %s:\n    <<: *backend-common\n    command: %s\n    environment:\n      <<: *backend-env\n      METRICS_PORT: %s\n    ports:\n      - \"%s:%s\"\n\n", name, renderLoggedCommand(name, "./cmd/"+name), def.DefaultPort, def.DefaultPort, def.DefaultPort)
}

func renderFrontendService() string {
	return "  frontend:\n    image: node:20\n    working_dir: /app/frontend\n    command: sh -c 'npm install && npm run dev -- --host 0.0.0.0 --port 5173'\n    volumes:\n      - ./:/app\n    ports:\n      - \"5173:5173\"\n    depends_on:\n      gateway:\n        condition: service_started\n\n"
}

func renderInfraServices() string {
	return `  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: game_admin
      MYSQL_USER: gameadmin
      MYSQL_PASSWORD: gameadmin
      MYSQL_ROOT_PASSWORD: root
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    image: prom/prometheus:v2.55.1
    profiles: ["observability"]
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./deploy/observability/prometheus.microservices.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      gateway:
        condition: service_started
      identity-service:
        condition: service_started
      tenant-service:
        condition: service_started
      agent-service:
        condition: service_started
      relation-service:
        condition: service_started
      game-service:
        condition: service_started
      rule-service:
        condition: service_started
      activity-service:
        condition: service_started
      recharge-service:
        condition: service_started
      settlement-service:
        condition: service_started
      account-service:
        condition: service_started
      withdrawal-service:
        condition: service_started
      risk-service:
        condition: service_started
      report-service:
        condition: service_started
      audit-service:
        condition: service_started
      notification-service:
        condition: service_started
      data-platform-sync-service:
        condition: service_started

  loki:
    image: grafana/loki:3.1.1
    profiles: ["observability"]
    command:
      - -config.file=/etc/loki/config.yml
    volumes:
      - ./deploy/observability/loki-config.yml:/etc/loki/config.yml:ro
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.1.1
    profiles: ["observability"]
    command:
      - -config.file=/etc/promtail/config.yml
    volumes:
      - ./deploy/observability/promtail-config.yml:/etc/promtail/config.yml:ro
      - ./deploy/observability/logs:/var/log/game-admin:ro
    depends_on:
      loki:
        condition: service_started

  grafana:
    image: grafana/grafana:11.1.4
    profiles: ["observability"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./deploy/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    profiles: ["observability"]
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
`
}

func renderLoggedCommand(serviceName, target string) string {
	return fmt.Sprintf("[\"bash\", \"-lc\", \"mkdir -p /app/deploy/observability/logs && exec > >(tee -a /app/deploy/observability/logs/%s.log) 2>&1; go run %s\"]", serviceName, target)
}

func gatewayEnvKey(serviceName string) string {
	switch strings.TrimSpace(serviceName) {
	case "data-platform-sync-service":
		return "DATA_SYNC"
	default:
		return strings.ToUpper(strings.ReplaceAll(strings.TrimSuffix(serviceName, "-service"), "-", "_"))
	}
}
