package config_test

import (
	"path/filepath"
	"testing"

	"game-admin/backend/internal/config"
	"github.com/stretchr/testify/require"
)

func TestLoadDefaults(t *testing.T) {
	t.Setenv("APP_ENV", "")
	t.Setenv("HTTP_PORT", "")
	t.Setenv("DATABASE_DRIVER", "")
	t.Setenv("DATABASE_DSN", "")
	t.Setenv("REDIS_ENABLED", "")
	t.Setenv("REDIS_ADDR", "")
	t.Setenv("REDIS_PASSWORD", "")
	t.Setenv("REDIS_DB", "")
	t.Setenv("REDIS_PREFIX", "")
	t.Setenv("MQ_ENABLED", "")
	t.Setenv("MQ_DRIVER", "")
	t.Setenv("MQ_URL", "")
	t.Setenv("MQ_TOPIC", "")
	t.Setenv("TELEMETRY_ENABLED", "")
	t.Setenv("TELEMETRY_EXPORTER", "")
	t.Setenv("OTEL_EXPORTER_OTLP_ENDPOINT", "")
	t.Setenv("OTEL_EXPORTER_OTLP_INSECURE", "")
	t.Setenv("SERVICE_VERSION", "")
	t.Setenv("BACKEND_ROOT", "")
	t.Setenv("FRONTEND_ROOT", "")

	cfg := config.Load()

	require.Equal(t, "development", cfg.Env)
	require.Equal(t, "8080", cfg.HTTPPort)
	require.Equal(t, "sqlite", cfg.Database.Driver)
	require.Equal(t, "data/app.db", cfg.Database.DSN)
	require.False(t, cfg.Redis.Enabled)
	require.Equal(t, "localhost:6379", cfg.Redis.Addr)
	require.Equal(t, "", cfg.Redis.Password)
	require.Equal(t, 0, cfg.Redis.DB)
	require.Equal(t, "game-admin:", cfg.Redis.Prefix)
	require.False(t, cfg.MQ.Enabled)
	require.Equal(t, "rabbitmq", cfg.MQ.Driver)
	require.Equal(t, "amqp://guest:***@localhost:5672/", cfg.MQ.URL)
	require.Equal(t, "game-admin.events", cfg.MQ.Topic)
	require.False(t, cfg.Telemetry.Enabled)
	require.Equal(t, "none", cfg.Telemetry.Exporter)
	require.Equal(t, "", cfg.Telemetry.OTLPEndpoint)
	require.False(t, cfg.Telemetry.OTLPInsecure)
	require.Equal(t, "dev", cfg.Telemetry.ServiceVersion)
	require.Equal(t, ":8080", cfg.Address())
	require.Equal(t, ".", cfg.BackendRoot())
	require.Equal(t, filepath.Join("..", "frontend"), cfg.FrontendRoot())
	require.Contains(t, cfg.InitSummary(), "APP_ENV=development")
}

func TestLoadFromEnvironment(t *testing.T) {
	t.Setenv("APP_ENV", "test")
	t.Setenv("HTTP_PORT", "9090")
	t.Setenv("DATABASE_DRIVER", "mysql")
	t.Setenv("DATABASE_DSN", ":memory:")
	t.Setenv("REDIS_ENABLED", "true")
	t.Setenv("REDIS_ADDR", "redis:6379")
	t.Setenv("REDIS_PASSWORD", "secret")
	t.Setenv("REDIS_DB", "2")
	t.Setenv("REDIS_PREFIX", "test:")
	t.Setenv("MQ_ENABLED", "true")
	t.Setenv("MQ_DRIVER", "kafka")
	t.Setenv("MQ_URL", "kafka://broker:9092")
	t.Setenv("MQ_TOPIC", "events.test")
	t.Setenv("TELEMETRY_ENABLED", "true")
	t.Setenv("TELEMETRY_EXPORTER", "otlp")
	t.Setenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://otel-collector:4318")
	t.Setenv("OTEL_EXPORTER_OTLP_INSECURE", "true")
	t.Setenv("SERVICE_VERSION", "2026.04.28")
	t.Setenv("BACKEND_ROOT", "/tmp/backend")
	t.Setenv("FRONTEND_ROOT", "/tmp/frontend")

	cfg := config.Load()

	require.Equal(t, "test", cfg.Env)
	require.Equal(t, "9090", cfg.HTTPPort)
	require.Equal(t, "mysql", cfg.Database.Driver)
	require.Equal(t, ":memory:", cfg.Database.DSN)
	require.True(t, cfg.Redis.Enabled)
	require.Equal(t, "redis:6379", cfg.Redis.Addr)
	require.Equal(t, "secret", cfg.Redis.Password)
	require.Equal(t, 2, cfg.Redis.DB)
	require.Equal(t, "test:", cfg.Redis.Prefix)
	require.True(t, cfg.MQ.Enabled)
	require.Equal(t, "kafka", cfg.MQ.Driver)
	require.Equal(t, "kafka://broker:9092", cfg.MQ.URL)
	require.Equal(t, "events.test", cfg.MQ.Topic)
	require.True(t, cfg.Telemetry.Enabled)
	require.Equal(t, "otlp", cfg.Telemetry.Exporter)
	require.Equal(t, "http://otel-collector:4318", cfg.Telemetry.OTLPEndpoint)
	require.True(t, cfg.Telemetry.OTLPInsecure)
	require.Equal(t, "2026.04.28", cfg.Telemetry.ServiceVersion)
	require.Equal(t, ":9090", cfg.Address())
	require.Equal(t, "/tmp/backend", cfg.BackendRoot())
	require.Equal(t, "/tmp/frontend", cfg.FrontendRoot())
	require.Contains(t, cfg.InitSummary(), "MQ_ENABLED=true")
}
