server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: game-admin-services
    static_configs:
      - targets:
          - localhost
        labels:
          job: game-admin-services
          __path__: /var/log/game-admin/*.log
    relabel_configs:
      - source_labels: [__path__]
        regex: .*/(.*)\.log
        target_label: service
        replacement: $1
